apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voting-backend
  template:
    metadata:
      labels:
        app: voting-backend
    spec:
      containers:
        - name: backend
          image: voting-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "sqlite:///./test.db"
